spring.application.name=demo_bookmark

# 1) connect DB
spring.datasource.url=jdbc:mysql://localhost:3306/demo_bookmark?useSSL=false&serverTimezone=Asia/Bangkok&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# 2) (Tu? ch?n) Driver - th??ng Spring t? ?oán ???c n?u có url, nh?ng ghi rõ c?ng OK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3) Basic JPA config ///// create = t? tao code + drop DB / update = sync nh? nh?ng không drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect